### ISSUE TITLE
[Question] ORPO + SFTTrainer + QLora 

### ISSUE THREAD

**Issue by snassimr** [xfactlab/orpo#10]
Hi ,

If it's posible to train ORPO with SFTTrainer and QLora ?

Thanks

**Comment by nlee-208** [comment]
Hi @snassimr, 

If you are referring to applying the SFTTrainer directly on ORPO, it wouldn't be feasible as ORPO simultaneously trains on the preference pair data via odds-ratio.

Relating to QLoRA, we have plans to integrate the PEFT methods in the near future but note that QLoRA may not work well with ZeRO Stage 3 or FSDP ([related reddit](https://www.reddit.com/r/LocalLLaMA/comments/1ai5mv3/thoughts_on_qlora_with_fsdp/?sort=new)). If you are in need of immediate implementation feel free to try the [TRL ORPO](https://huggingface.co/docs/trl/trainer#trl.ORPOTrainer) implementation.
