### ISSUE TITLE
how to do ORPO with ShareGPT data?

### ISSUE THREAD

**Issue by pabl-o-ce** [xfactlab/orpo#11]
is there a way to modify a current dataset ShareGPT to ORPO?

**Comment by nlee-208** [comment]
Hi @pabl-o-ce, 

If you're talking about the [ShareGPT_Vicuna_unfiltered](https://huggingface.co/datasets/anon8231489123/ShareGPT_Vicuna_unfiltered) dataset, it does not have a pairwise preference format necessary for ORPO. So in that case you can further develop pairs based on the dataset or maybe use it to perform SFT before applying ORPO.

**Comment by pabl-o-ce** [comment]
Hi @nlee-208 yeah the main problem I was looking is to generate the negative response for complete a dataset that is on sharegpt
