### ISSUE TITLE
Can you please give us a guide line to use your method to train on the LLAMA factory?

### ISSUE THREAD

**Issue by TonyQJH** [xfactlab/orpo#20]
I would be grateful if you could also provide sample training data that can be used in the llama-factory, and tell us the meaning of each row in the output.

**Comment by jiwooya1000** [comment]
Hello @TonyQJH,

Thank you for the good suggestion.
As we currently only have the demo code for our code base and TRL, we will work on adding the demo code for LLaMA-Factory. 

I will notify you through this issue as soon as we have the demo code with LLaMA-Factory
