### ISSUE TITLE
Memory Consumption

### ISSUE THREAD

**Issue by paulcx** [xfactlab/orpo#22]
Thank you very much for your work, it's been excellent.

As shown in the example of trl/test_orpo_trainer_demo.py, I' wondering that compared with sft training where chosen and rejected data will be concated together, both memory and gpu memory will double as a result of this, right?

**Comment by jiwooya1000** [comment]
Hello @paulcx, thank you for saying that😃

Yes, it is correct that ORPO's memory consumption is approximately twice that of SFT, as there isn't any reference model to conduct additional forward passes.
