### ISSUE TITLE
Is there any statement error in 4.2 of the paper？

### ISSUE THREAD

**Issue by Chic-star** [xfactlab/orpo#25]
Is there any statement error in 4.2 of the paper, such as: “LOR in Equation 7 maximizes the odds ratio between the likelihood of generating the disfavored response yw and the  disfavored response yl. ", please check the published papers carefully.

**Comment by jiwooya1000** [comment]
Yes there is an error in the part you mentioned and we confirm that there aren't any error in Section 4.2.
And this will be fixed soon in our final version of the paper.

> LOR in Equation 7 maximizes the odds ratio between the likelihood of generating the disfavored response yw and the disfavored response yl

**Comment by Chic-star** [comment]
我已收到。
